### PR TITLE
Add test for methods

### LINKED ISSUE #5: Add tests to methods
Hi @vincentrou,

Could you please add some tests to these methods? My gutt feeling tells me some code from the `diff_drive_controller` could be leveraged but not sure.

### PR DESCRIPTION
**Pull request by vincentrou**
fix #5

### CODE REVIEW

**Comment by bmagyar** [comment]
@matthew-reynolds do you have a bit of spare bandwidth to shake this into shape before we go into Noetic?

**Comment by matthew-reynolds** [comment]
@bmagyar I'm a bit swamped with navigating exams amid all the COVID-19 uncertainty, but I should have some time next week.

A quick scan looks to me like with a little bit of cleanup, and maybe adding a test for `getTransformVector()`, this is a good simple first test of the main functions. I think that's probably sufficient for now (Definitely better than nothing!) and we can follow-up to add more complex test cases in the future. Does that sound good from your perspective?

**Comment by bmagyar** [comment]
Absolutely! Since these are mostly tests, adding them to kinetic too should be fine

**Comment by matthew-reynolds** [comment]
Closing in favour of #13

**Pull request closed without merging**
